openapi: 3.0.0
info:
  version: 1.0.0
  title: IBM-SL
servers:
  - url: https://ibm-sl-api.deno.dev/
    description: Production server
  - url: http://localhost:8000
    description: Local server
components:
  schemas: {}
  parameters: {}
paths:
  /api/estimate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                list:
                  type: array
                  items:
                    type: object
                    properties:
                      transport_form:
                        type: string
                        enum:
                          - road
                          - train
                          - aircraft
                          - cargoship
                      distance_km:
                        type: number
                    required:
                      - transport_form
                      - distance_km
                  description: >-
                    List of objects that contains a 'transport_form' and its
                    'distance_km'
                  example:
                    - transport_form: road
                      distance_km: 100
                    - transport_form: train
                      distance_km: 500
                    - transport_form: aircraft
                      distance_km: 300
                    - transport_form: cargoship
                      distance_km: 300
              required:
                - list
      responses:
        '200':
          description: Retrieve total estimated emission
          content:
            application/json:
              schema:
                estimate:
                  _def:
                    checks: []
                    typeName: ZodNumber
                    coerce: false
                    openapi:
                      metadata:
                        example: 1000
        '400':
          description: Returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 400
                  message:
                    type: string
                    example: Bad Request
                required:
                  - code
                  - message
